### ISSUE TITLE
level ranks no longer loads since the sticker update

### ISSUE THREAD

**Issue by freakexeuLow** [Pisex/cs2-lvl_ranks#2]
Hey Pisex,
since the last big update level ranks doesn't work anymore (i think you are aware of that) hope the project will continue to be updated :)

thanks for your work 👍🏼

**Comment by kolibrzyk** [comment]
Check pull requests ...

**Comment by freakexeuLow** [comment]
> Check pull requests ...

done and would you also attach the compiled version for linux in your pull request?

**Comment by freakexeuLow** [comment]
CLOSED, BECAUSE IS LOADING NOW! Thanks @exababy
