### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ghostt187** [Pisex/cs2-lvl_ranks#4]
Crashes the server after a couple of minutes

**Comment by freakexeuLow** [comment]
> Crashes the server after a couple of minutes

yeah, same problem

**Comment by Bullzai** [comment]
I suspect it's the mysql_mm at fault here. Same goes for bans plugin
https://github.com/Poggicek/mysql_mm

**Comment by freakexeuLow** [comment]
maybe, someone already try to push a pull request here: [https://github.com/Poggicek/mysql_mm/pull/8](https://github.com/Poggicek/mysql_mm/pull/8)

**Comment by ghostt187** [comment]
> maybe, someone already try to push a pull request here: [Poggicek/mysql_mm#8](https://github.com/Poggicek/mysql_mm/pull/8)

weird cuz some other meta plugins arent crashing

**Comment by freakexeuLow** [comment]
> > maybe, someone already try to push a pull request here: [Poggicek/mysql_mm#8](https://github.com/Poggicek/mysql_mm/pull/8)
> 
> weird cuz some other meta plugins arent crashing

that's true, I also use the admin system of pisex, which is also connected to mysql_mm

**Comment by Bullzai** [comment]
> > > maybe, someone already try to push a pull request here: [Poggicek/mysql_mm#8](https://github.com/Poggicek/mysql_mm/pull/8)
> > 
> > 
> > weird cuz some other meta plugins arent crashing
> 
> that's true, I also use the admin system of pisex, which is also connected to mysql_mm

same, but whenever I use !gag !mute or !ban the server crashes. Kick & slay works fine tho. Hence why I was suspecting the mysql plugin

**Comment by ghostt187** [comment]
gotta ask the author of mysql mm to check if it needs any updates

**Comment by Bullzai** [comment]
I just did, he said "probably just has to be recompiled with latest sdk" - trying that as well.

**Comment by freakexeuLow** [comment]
i think it should work after the pull request exababy also made the pull request for level ranks he must have been thinking of something^^

**Comment by ghostt187** [comment]
> I just did, he said "probably just has to be recompiled with latest sdk" - trying that as well.

if it works let us know

**Comment by Bullzai** [comment]
> > I just did, he said "probably just has to be recompiled with latest sdk" - trying that as well.
> 
> if it works let us know

unfortunately still the same even after updating mysql_mm & building it with latest SDK. Might be a problem somewhere else then?

**Comment by ghostt187** [comment]
> > > I just did, he said "probably just has to be recompiled with latest sdk" - trying that as well.
> > 
> > 
> > if it works let us know
> 
> unfortunately still the same even after updating mysql_mm & building it with latest SDK. Might be a problem somewhere else then?

did u try the latest mysql poggu changed some things

**Comment by Bullzai** [comment]
> > > > I just did, he said "probably just has to be recompiled with latest sdk" - trying that as well.
> > > 
> > > 
> > > if it works let us know
> > 
> > 
> > unfortunately still the same even after updating mysql_mm & building it with latest SDK. Might be a problem somewhere else then?
> 
> did u try the latest mysql poggu changed some things

Yeah, I'm chatting with him via discord. His mysql_mm plugin seems to work as it should.

After the update a lot of sigs and offsets just broke and mysql_mm has none of that - which now makes me think there's an issue in bans/ranks, rather than in mysql_mm.

Will try to run servers in gdb once I find some more time to troubleshoot.

**Comment by Pisex** [comment]
No idea what the problem is, because with the older version all my plugins work fine, but as soon as I try the new version anything stops working

**Comment by Pisex** [comment]
> No idea what the problem is, because with the older version all my plugins work fine, but as soon as I try the new version anything stops working

Well, it works, but not all the time.

**Comment by ghostt187** [comment]
the guy who pulled the request tried a lot of things did u take a look if maybe he changed some things wrong

> > No idea what the problem is, because with the older version all my plugins work fine, but as soon as I try the new version anything stops working
> 
> Well, it works, but not all the time.

**Comment by Bullzai** [comment]
> > No idea what the problem is, because with the older version all my plugins work fine, but as soon as I try the new version anything stops working
> 
> Well, it works, but not all the time.

does your admin system not crash your servers immediately after trying to !ban !mute or !gag? It seems like whenever it tries to insert data into SQL it just crashes. Same goes for ranks (at least for me)

**Comment by Pisex** [comment]
> > > No idea what the problem is, because with the older version all my plugins work fine, but as soon as I try the new version anything stops working
> > 
> > 
> > Well, it works, but not all the time.
> 
> does your admin system not crash your servers immediately after trying to !ban !mute or !gag? It seems like whenever it tries to insert data into SQL it just crashes. Same goes for ranks (at least for me)

There was a problem when accessing the Escape function in mysql_mm before the update, but now I have no idea why it works like that, it doesn't always handle the query I send out

**Comment by Bullzai** [comment]
> > > > No idea what the problem is, because with the older version all my plugins work fine, but as soon as I try the new version anything stops working
> > > 
> > > 
> > > Well, it works, but not all the time.
> > 
> > 
> > does your admin system not crash your servers immediately after trying to !ban !mute or !gag? It seems like whenever it tries to insert data into SQL it just crashes. Same goes for ranks (at least for me)
> 
> There was a problem when accessing the Escape function in mysql_mm before the update, but now I have no idea why it works like that, it doesn't always handle the query I send out

After building mysql_mm with latest SDK I started getting this:

����eamid` VARCHAR(32) NOT NULL, `steamid` VARCHAR(32) NOT NULL, `name` VARCHAR(64) NOT NULL, `admin_name` VARCHAR(64) NOT NULL, `created` INTEGER NOT NULL, `duration` INTEGER NOT NULL, `end` INTEGER NOT NULL, `reason` VARCHAR(64) NOT NULL);eamid` VARCHAR(32) NOT NULL, `steamid` VARCHAR(32) NOT NULL, `name` VARCHAR(64) NOT NULL, `admin_name` VARCHAR(64) NOT NULL, `created` INTEGER NOT NULL, `duration` INTEGER NOT NULL, `end` INTEGER NOT NULL, `reason` VARCHAR(64) NOT NULL);

Which was caused by error buffer according to Poggu, then he did those updates and everything seemed to work again with latest SDK, but the server crashes remained upon trying to insert any data into SQL.

Hopefully this will give you some insights.

**Comment by freakexeuLow** [comment]
@Pisex it looks good now, thanks for the update 👍🏼

**Comment by ghostt187** [comment]
> @Pisex it looks good now, thanks for the update 👍🏼

which version

**Comment by freakexeuLow** [comment]
> > @Pisex it looks good now, thanks for the update 👍🏼
> 
> which version

[https://github.com/Pisex/cs2-lvl_ranks/releases/tag/1.0.1_Fix](https://github.com/Pisex/cs2-lvl_ranks/releases/tag/1.0.1_Fix)

**Comment by ghostt187** [comment]
uptime?

**Comment by freakexeuLow** [comment]
> uptime?

currently 20 min...have played several rounds on it and also tested the admin menu, both no longer lead to a crash

**Comment by Bullzai** [comment]
@Pisex can confirm it's working fine now as well. Thanks!

Out of curiosity, what was wrong? I don't see any new commits, just updated releases.

Edit: Slay doesn't seem to work? @freakexeuLow does it work for you? Also you seem to left debug mode on

**Comment by ghostt187** [comment]
@Pisex inside the release files is there the new mysql_mm or not?

**Comment by freakexeuLow** [comment]
> @Pisex inside the release files is there the new mysql_mm or not?

yes, it is

**Comment by ghostt187** [comment]
im curious what did change was the change inside .so file or the other files

**Comment by freakexeuLow** [comment]
> @Pisex can confirm it's working fine now as well. Thanks!
> 
> Out of curiosity, what was wrong? I don't see any new commits, just updated releases.
> 
> Edit: Slay doesn't seem to work? @freakexeuLow does it work for you? Also you seem to left debug mode on

have not tested this before with the admin system (slay)...but you should report it in the admin_system (github) instead of here and yes, the debug mode is still on


> im curious what did change was the change inside .so file or the other files

looks like this here: [https://github.com/Poggicek/mysql_mm/commit/b0d25205ea0060086da6b1bb7efb20f4d790ac7a](https://github.com/Poggicek/mysql_mm/commit/b0d25205ea0060086da6b1bb7efb20f4d790ac7a)

**Comment by ghostt187** [comment]
@Pisex can u disable back the debug mode

**Comment by ghostt187** [comment]
> > uptime?
> 
> currently 20 min...have played several rounds on it and also tested the admin menu, both no longer lead to a crash

any crashes?

**Comment by freakexeuLow** [comment]
> > > uptime?
> > 
> > 
> > currently 20 min...have played several rounds on it and also tested the admin menu, both no longer lead to a crash
> 
> any crashes?

nope, it works fine without any crash

**Comment by ghostt187** [comment]
crashed for me after 5 hours anyone else got crashes?

**Comment by ghostt187** [comment]
> > > > uptime?
> > > 
> > > 
> > > currently 20 min...have played several rounds on it and also tested the admin menu, both no longer lead to a crash
> > 
> > 
> > any crashes?
> 
> nope, it works fine without any crash

did u get any crashes?
